### ISSUE TITLE
Enchanced Security

### ISSUE THREAD

**Issue by szachovy** [szachovy/superset-cluster#19]
:warning: **_In the process_**

Security/Reliability improval ideas:
- [x] SELinux, AppArmor, Seccomp extended
- [x] [Docker bench](https://github.com/docker/docker-bench-security) with [trivy](https://github.com/aquasecurity/trivy)
- [x] [Cap adds/drops analysis](https://docs.docker.com/engine/containers/run/)
- [x] [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Secure_Product_Design_Cheat_Sheet.html#security-principles)
* Redis:
  - [x] Check and implement [official Redis setup tricks](https://redis.io/docs/latest/operate/oss_and_stack/management/admin/)
  - [x] Check and implement [security models and features in Redis](https://redis.io/docs/latest/operate/oss_and_stack/management/security/) + research options [redis.conf](https://redis.io/docs/latest/operate/oss_and_stack/management/config-file/)
* Superset:
  - [x] [Security configurations](https://superset.apache.org/docs/security/) + research [options](https://github.com/apache/superset/blob/master/superset/config.py)
* Management:
  - [x] [Options for InnoDB Cluster](https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-innodb-cluster-setting-options.html) with [instances](https://dev.mysql.com/doc/mysql-shell/8.0/en/add-instances-cluster.html)
  - [x] [Failover consistency](https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-innodb-cluster-failover-consistency.html)
  - [x] [Auto-increment offset](https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-innodb-cluster-auto-increment.html)
  - [x] [Instances rejoin (higher up)](https://dev.mysql.com/doc/mysql-shell/8.0/en/configuring-automatic-rejoin-of-instances.html)
  - [x] [Add verifications](https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-innodb-cluster-securing.html)
  - [x] Reseach [privileges and options](https://dev.mysql.com/doc/mysql-router/8.0/en/mysqlrouter.html#option_mysqlrouter_bootstrap) + [adjust router options](https://dev.mysql.com/doc/mysql-router/8.0/en/mysql-router-conf-options.html)
* MySQL:
  - [x] [Security guidelines](https://dev.mysql.com/doc/refman/8.4/en/security-guidelines.html)
  - [x] [Making MySQL Secure Against Attackers](https://dev.mysql.com/doc/refman/8.4/en/security-against-attack.html)
  - [x] [Loadable Function Security Precautions](https://dev.mysql.com/doc/extending-mysql/8.4/en/adding-loadable-function.html#loadable-function-security)
  - [x] Reseach on [SSL options](https://dev.mysql.com/doc/refman/8.4/en/connection-options.html#encrypted-connection-options)
  - [x] [Server Options, System Variables, and Status Variable References](https://dev.mysql.com/doc/refman/8.4/en/server-option-variable-reference.html) _([validation reference](https://dev.mysql.com/doc/refman/8.4/en/server-configuration-validation.html))_
  - [x] [Selinux](https://dev.mysql.com/doc/refman/8.4/en/selinux.html)
  - [x] [FIPS mode support](https://dev.mysql.com/doc/refman/8.4/en/fips-mode.html)
  - [x] [Backups](https://dev.mysql.com/doc/refman/8.4/en/backup-and-recovery.html) with [InnoDB specifics](https://dev.mysql.com/doc/refman/8.4/en/innodb-backup-recovery.html)
  - [x] [InnoDB Data-at-Rest Encryption](https://dev.mysql.com/doc/refman/8.4/en/innodb-data-encryption.html)
