### ISSUE TITLE
Performance Optimization

### ISSUE THREAD

**Issue by szachovy** [szachovy/superset-cluster#20]
:warning: **_In the process_**

Performance improval ideas:
- [x] Pre-pull images in the background
- [x] Disjoint operations in parallel (Python)
- [x] [Docker compose resources](https://docs.docker.com/reference/compose-file/services/)
- [x] [MySQL Tuner](https://github.com/major/MySQLTuner-perl)
- [x] Apache Benchmark
- [x] Use new Python modules (python .env)

* Redis
  - [x] [Optimize for memory](https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/memory-optimization/) with [general use CPU profiling](https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/cpu-profiling/) follow the measurements for https://github.com/szachovy/superset-cluster/issues/30#issue-2593000394
* Superset:
  - [x] Caching [fallback metastore + thumbnails](https://superset.apache.org/docs/configuration/cache/)
  - [x] [Gunicorn design alignment](https://docs.gunicorn.org/en/stable/design.html)
* Management:
  - [x] [Parallel Replication Applier](https://dev.mysql.com/doc/mysql-shell/8.0/en/configuring-parallel-applier.html)
  - [x] Checkout on [Connection Sharing and Reuse](https://dev.mysql.com/doc/mysql-router/8.0/en/mysql-router-general-features-connection-sharing.html)
* MySQL:
  * [Useful Architecture](https://dev.mysql.com/doc/refman/8.3/en/innodb-architecture.html)
    - [x] [Taking advantage of the buffer pool](https://dev.mysql.com/doc/refman/8.3/en/innodb-buffer-pool.html)
    - [x] [Decrease change buffer because of low DML ops, high read ops](https://dev.mysql.com/doc/refman/8.3/en/innodb-change-buffer.html)
    - [x] [Test if Adaptive Hash Index is necessary](https://dev.mysql.com/doc/refman/8.3/en/innodb-adaptive-hash.html)
    - [x] [Adjust Log Buffer mainly for read speed](https://dev.mysql.com/doc/refman/8.3/en/innodb-redo-log-buffer.html)
  - [x] [Compressions](https://dev.mysql.com/doc/refman/8.4/en/connection-options.html#connection-compression-options)
  - [x] [Optimization and Indexes](https://dev.mysql.com/doc/refman/8.4/en/optimization-indexes.html)
  - [x] [Optimizing Database Structure](https://dev.mysql.com/doc/refman/8.4/en/optimizing-database-structure.html)
  - [x] [Optimizing for InnoDB Tables](https://dev.mysql.com/doc/refman/8.4/en/optimizing-innodb.html)
  - [x] [Buffering and Caching](https://dev.mysql.com/doc/refman/8.4/en/buffering-caching.html)
  - [x] [Optimizing the MySQL Server](https://dev.mysql.com/doc/refman/8.4/en/optimizing-server.html)
  - [x] [InnoDB Advanced Configuration](https://dev.mysql.com/doc/refman/8.4/en/innodb-configuration.html)
  - [x] [InnoDB Table and Page Compression](https://dev.mysql.com/doc/refman/8.4/en/innodb-compression.html)
